

2016-03-24 20:52:01
error_test_cases : 
 E:/project_XMD/testcase\account : account.py 
 E:/project_XMD/testcase\data : data.py 
error : 2
success : 4
thread_time : 0.149000167847
